name: CI

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Setup nodejs
      uses: actions/setup-node@v1
      with:
        node-version: 12.21.0

    - name: Cache npm modules
      uses: actions/cache@v1
      with:
        path: ~/.npm
        key: ${{ runner.os }}-npm-${{ hashFiles('package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-npm-

    - name: Cache bower modules
      uses: actions/cache@v1
      with:
        path: bower_components
        key: ${{ runner.os }}-deps-${{ hashFiles('bower.json') }}
        restore-keys: |
          ${{ runner.os }}-deps-

    - name: Install dependencies
      run: npm ci

    - name: Test
      run: npm test
